/*	Drop existing table */
--DROP TABLE bu_ire.TERM_DATES_CTE;

/*	Delete data from table */
--DELETE FROM bu_ire.TERM_DATES_CTE;

/*	Recreate table with new definitions */
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE bu_ire.TERM_DATES_CTE
	(
		TERM VARCHAR(7) NOT NULL
		, TERM_DESC VARCHAR(40) NULL
		, TERM_SEASON VARCHAR(10) NULL
		, TEST_DATE DATETIME NULL
		, TERM_REG_DATE DATETIME NULL
		, TERM_START_DATE DATETIME NULL
		, TERM_CENSUS_DATE DATETIME NULL
		, TERM_END_DATE DATETIME NULL
		, BATES_STAMP INT NOT NULL
		, TERM_RPT_YR_STRING VARCHAR(4) NOT NULL
		, TERM_RPT_YR_NUMERIC INT NOT NULL
		, TERM_SEQ_NO TINYINT NOT NULL
		, TERM_SEQ VARCHAR(7) NOT NULL
		, COLLEAGUE_FLAG VARCHAR(1) NULL
		, LAST_TERM1 VARCHAR(10) NULL
		, LAST_TERM2 VARCHAR(10) NULL
		, UPDATE_DATE DATETIME
		, CONSTRAINT YEAR_TERM_DATE_STAMP PRIMARY KEY (TERM_RPT_YR_NUMERIC ASC, TERM_SEQ_NO ASC, BATES_STAMP ASC)
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
GO

/*	Create table indices */
CREATE INDEX IDX_TERM_SEQ ON bu_ire.TERM_DATES_CTE (TERM_SEQ);
CREATE INDEX IDX_TERM ON bu_ire.TERM_DATES_CTE (TERM);


/*	Rebuild data in table */
;WITH TERM_CTE (TERM, TEST_DATE, BATES_STAMP, TERM_END_DATE, LAST_TERM1, LAST_TERM2) AS
	(
		SELECT
			T.TERMS_ID AS TERM
			, T.B13_TERM_REG_START_DATE AS TEST_DATE
			, DATEDIFF(DAY, T.TERM_START_DATE, T.B13_TERM_REG_START_DATE) AS BATES_STAMP
			, T.TERM_END_DATE
			, CASE RIGHT(T.TERMS_ID,2)
					WHEN 'FA' THEN LEFT(T.TERMS_ID,4)+'SU'
					WHEN 'SU' THEN LEFT(T.TERMS_ID,4)+'SP'
					WHEN 'SP' THEN CONVERT(VARCHAR(4),CAST(LEFT(T.TERMS_ID,4) AS INT)-1)+'FA'
				END AS LAST_TERM1
			, CASE RIGHT(T.TERMS_ID,2)
					WHEN 'FA' THEN LEFT(T.TERMS_ID,4)+'SP'
					WHEN 'SU' THEN CONVERT(VARCHAR(4),CAST(LEFT(T.TERMS_ID,4) AS INT)-1)+'FA'
					WHEN 'SP' THEN CONVERT(VARCHAR(4),CAST(LEFT(T.TERMS_ID,4) AS INT)-1)+'SU'
				END AS LAST_TERM2

		FROM
			ODS_TERMS T

		WHERE
			RIGHT(T.TERMS_ID,2) IN ('FA', 'SP', 'SU')
			--AND T.TERM_REPORTING_YEAR >= 2016
			AND T.B13_TERM_REG_START_DATE <= GETDATE()

		UNION ALL

		SELECT
			T.TERM
			, DATEADD(DAY, 1, T.TEST_DATE)
			, T.BATES_STAMP+1
			, T.TERM_END_DATE
			, T.LAST_TERM1
			, T.LAST_TERM2
		
		FROM
			TERM_CTE T
		
		WHERE
			T.TEST_DATE <= DATEADD(DAY, -1, GETDATE())
			AND T.TEST_DATE <= DATEADD(DAY, 10, T.TERM_END_DATE)
	)

/* remove comment from line below to copy & paste into SQL Server Agent */
INSERT INTO bu_ire.TERM_DATES_CTE

SELECT
	T.TERM
	, TM.TERM_DESC
	, CASE RIGHT(T.TERM,2)
			WHEN 'FA' THEN 'Fall'
			WHEN 'SP' THEN 'Spring'
			WHEN 'SU' THEN 'Summer'
		END AS TERM_SEASON
	, T.TEST_DATE
	, TM.B13_TERM_REG_START_DATE AS TERM_REG_DATE
	, TM.TERM_START_DATE
	, TM.B13_TERM_CENSUS_DATE AS TERM_CENSUS_DATE
	, TM.TERM_END_DATE
	, T.BATES_STAMP
	, CONVERT(VARCHAR(4),TM.TERM_REPORTING_YEAR) AS TERM_RPT_YR_STRING
	, CAST(TM.TERM_REPORTING_YEAR AS INT) AS TERM_RPT_YR_NUMERIC
	, TM.B13_TERM_SEQUENCE_NO AS TERM_SEQ_NO
	, CONVERT(VARCHAR(4),TM.TERM_REPORTING_YEAR)+'*'+CONVERT(VARCHAR(1),TM.B13_TERM_SEQUENCE_NO) AS TERM_SEQ
	, CASE
			WHEN TM.TERM_REPORTING_YEAR >= '2016' THEN 'Y'
			ELSE 'N'
		END AS COLLEAGUE_FLAG
	, T.LAST_TERM1
	, T.LAST_TERM2
	, GETDATE() AS UPDATE_DATE
	
FROM
	TERM_CTE T
	JOIN ODS_TERMS TM ON T.TERM=TM.TERMS_ID

ORDER BY TM.TERM_REPORTING_YEAR, TM.B13_TERM_SEQUENCE_NO, T.BATES_STAMP
OPTION (MAXRECURSION 1000)


/*	Confirm data loaded correctly */
SELECT *
FROM bu_ire.TERM_DATES_CTE
ORDER BY 11, 12, 9


/*	Revision history:
		JDT 6/4/2020: Changed origin date (pivot date for BATES_STAMP) from census day to the first day of the term.
		JDT 4/13/2020: Added last term 1 and 2.
		JDT 12/2/2019: Updated column definitions to align with other files used in the student enrollment comparisons project.
		JDT 11/26/2019: Created file.
*/
